# Generated by Django 6.0.2 on 2026-02-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='patient_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
