# Generated by Django 6.0.2 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_patientpasswordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="doctors/"),
        ),
    ]
