# Generated by Django 6.0.2 on 2026-03-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_doctorprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consulted_status',
            field=models.CharField(choices=[('Consulted', 'Consulted'), ('Not Consulted', 'Not Consulted')], default='Not Consulted', max_length=20),
        ),
    ]
