# Generated by Django 6.0.2 on 2026-03-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_appointment_consulted_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Patient'), (2, 'Admin'), (3, 'Doctor')], default=1),
        ),
    ]
