# Generated by Django 6.0.2 on 2026-03-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
