# Generated by Django 6.0.2 on 2026-03-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_patient_created_at_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
