# Generated by Django 6.0.2 on 2026-05-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_appointment_consulted_status_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
